apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
  namespace: roboshop
  labels: 
    project: roboshop
    component: mongodb
    tier: db
spec:
  replicas: 1
  selector:
   # these labels are used to select pods
    matchLabels:
      project: roboshop
      component: mongodb
      tier: db
  template:
    metadata:
      labels:
        project: roboshop
        component: mongodb
        tier: db
    spec:
      containers:
      - name: mongodb
        image: shivaraju529/mongodb:v1
    

        

       
